services:
  - type: web
    name: extracto-ocr-api
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt && apt-get update && apt-get install -y tesseract-ocr
    startCommand: python ocr.py
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://extracto-ocr-frontend.onrender.com

  - type: static
    name: extracto-ocr-frontend
    rootDir: ocr-frontend
    buildCommand: ""
    staticPublishPath: .
