services:
  - type: web
    name: extracto-ocr-api
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://extracto-ocr-frontend.onrender.com

  - type: static
    name: extracto-ocr-frontend
    rootDir: ocr-frontend
    buildCommand: ""
    staticPublishPath: .
